name: Backup Neon DB to S3

on:
  schedule:
    - cron: '0 2 * * *' # Every day at 2:00 AM UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Set timestamp
        id: timestamp
        run: echo "TIME=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_ENV

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Dump Neon database
        run: |
          pg_dump \
            -h ${{ secrets.NEON_DB_HOST }} \
            -U ${{ secrets.NEON_DB_USER }} \
            -d ${{ secrets.NEON_DB_NAME }} \
            --no-owner --no-privileges \
            -F c \
            -f backup_${{ env.TIME }}.dump
        env:
          PGPASSWORD: ${{ secrets.NEON_DB_PASSWORD }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp backup_${{ env.TIME }}.dump s3://${{ secrets.S3_BUCKET_NAME }}/backups/backup_${{ env.TIME }}.dump
