name: Restore Neon DB from S3

on:
  workflow_dispatch:  # Manual trigger

jobs:
  restore:
    runs-on: ubuntu-latest

    steps:
      - name: Set up PostgreSQL and AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client awscli

      - name: Download backup from S3
        run: |
          aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/${{ secrets.BACKUP_FILE_KEY }} restore.dump
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Restore backup to Neon
        run: |
          PGPASSWORD=${{ secrets.NEON_DB_PASSWORD }} pg_restore \
            -h ${{ secrets.NEON_DB_HOST }} \
            -U ${{ secrets.NEON_DB_USER }} \
            -d ibookingv2 \
            --clean \
            --no-owner \
            --no-privileges \
            restore.dump
